import { chromium } from '@playwright/test';
const browser = await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1280,height:720}});page.setDefaultTimeout(120000);
page.on('console',m=>{if(m.type()==='error')console.log(m.type(),m.text());});
page.on('pageerror',e=>console.log('PAGEERROR',e.stack));
await page.goto('http://localhost:5173');
await page.waitForFunction(()=>!!window.__gameTest,{timeout:60000});
await page.evaluate(()=>{const g=window.__gameTest.game;g.settings.quality='Low';g.applySettings();});
await page.screenshot({path:'artifacts/menu.png'});
console.log('mesh',await page.evaluate(()=>{const g=window.__gameTest.game;return {camera:g.player.camera.position.asArray(),mat:g.map.scene.meshes.slice(0,8).map(m=>({name:m.name,p:m.position.asArray(),world:m.getAbsolutePosition().asArray(),enabled:m.isEnabled()}))};}));
await page.getByRole('button',{name:'Play',exact:false}).first().click();
await page.waitForTimeout(1000);
if(await page.getByRole('button',{name:'Resume',exact:true}).isVisible())await page.getByRole('button',{name:'Resume',exact:true}).click();
await page.waitForTimeout(1000);
console.log(await page.evaluate(()=>({lock:!!document.pointerLockElement,...window.__gameTest.snapshot()})));
await page.screenshot({path:'artifacts/wave1.png'});
await page.goto(new URL('../../dist/index.html', import.meta.url).href);
await page.getByRole('link',{name:'Open the game',exact:true}).waitFor();
await page.screenshot({path:'artifacts/file-launch.png'});
console.log('PASS: directly opened compiled HTML shows launch instructions.');
await browser.close();
