import { chromium, firefox } from '@playwright/test';
import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';
const production=process.env.PRODUCTION==='1';
const browserType=process.env.BROWSER==='firefox'?firefox:chromium;
const browser=await browserType.launch({headless:true,args:browserType===chromium?['--no-sandbox','--enable-unsafe-swiftshader']:[]});
const page=await browser.newPage({viewport:{width:1100,height:760}});page.setDefaultTimeout(120000);
const errors=[],requests=[],passed=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('request',r=>requests.push(r.url()));
await page.route('**/*',route=>{const u=route.request().url();if(u.startsWith('http://localhost:')||u.startsWith('data:')||u.startsWith('blob:'))route.continue();else route.abort();});
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const report=name=>{passed.push(name);console.log('PASS',name);};
const evaluate=fn=>page.evaluate(fn);
const snap=()=>evaluate(()=>window.__gameTest.snapshot());
const advance=n=>page.evaluate(n=>window.__gameTest.advance(n),n);
const trigger=async()=>{
  await page.mouse.down();await page.mouse.up();
};
const verifyMap=async()=>{const result=await evaluate(()=>{const g=window.__gameTest.game,n=g.map.nav,start=g.map.playerSpawns[0];return {supplies:g.map.supplies.every(s=>n.clear(s.position.x,s.position.z,s.position.y-.5)),interiors:g.map.enemySpawns.filter(s=>Math.abs(s.x)<29).map(s=>{const route=n.path({x:start.x,z:start.z,y:0},s),end=route.at(-1);return {s,end,ok:!!end&&Math.hypot(end.x-s.x,end.z-s.z)<2.2};})};});assert(result.supplies,JSON.stringify(result));assert(result.interiors.every(r=>r.ok),JSON.stringify(result));};
async function ready(){await page.waitForFunction(()=>window.__gameTest?.snapshot().state==='Playing',null,{timeout:120000});}
try{
  await page.goto(process.env.GAME_URL??(production?'http://localhost:4173':'http://localhost:5173'));
  await page.getByRole('button',{name:'How to Play'}).waitFor({timeout:60000});
  assert(await page.getByRole('heading',{name:/IDF/}).isVisible());report('Main menu and WebGL startup');
  await page.getByRole('button',{name:'How to Play'}).click();assert(await page.getByText('W A S D',{exact:true}).isVisible());await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.getByRole('button',{name:'Credits',exact:true}).click();assert(await page.getByText(/Game design, code, maps/).isVisible());await page.getByRole('button',{name:'Back',exact:true}).click();
  await page.getByRole('button',{name:'Settings',exact:false}).click();
  await page.getByLabel('Graphics quality').selectOption('Low');
  await page.getByLabel('Field of view').fill('85');
  await page.getByLabel('Music volume').fill('0.1');
  await page.getByRole('button',{name:'Back',exact:true}).click();report('Help, credits and runtime settings');
  await page.getByRole('button',{name:'Fullscreen',exact:false}).click();
  await page.waitForFunction(()=>!!document.fullscreenElement);report('Fullscreen user gesture');
  await page.screenshot({path:`artifacts/${production?'production-':''}menu.png`});
  await page.getByRole('button',{name:'Play',exact:false}).first().click();
  if(production){
    // wait for the wave to finish loading (shaders compile behind the loading screen): input is ignored until then
    await page.waitForFunction(()=>!document.querySelector('#hud')?.classList.contains('hidden'),null,{timeout:300000});await page.waitForTimeout(500);
    if(await page.getByRole('button',{name:'Resume',exact:true}).isVisible())await page.getByRole('button',{name:'Resume',exact:true}).click();
    assert(await evaluate(()=>!!document.pointerLockElement));
    assert(await evaluate(()=>!('__gameTest' in window)));
    await page.keyboard.down('KeyW');await page.waitForTimeout(500);await page.keyboard.up('KeyW');
    await trigger();await page.keyboard.press('Digit2');await trigger();
    await page.waitForFunction(()=>document.querySelector('.ammo-value')?.textContent.trim().startsWith('14'));
    assert.match(await page.locator('.ammo-value').innerText(),/reserve/i);
    await page.keyboard.press('KeyR');await page.waitForFunction(()=>document.querySelector('.status')?.textContent.includes('RELOADING'));
    await page.waitForFunction(()=>document.querySelector('.ammo-value')?.textContent.trim().startsWith('15'),null,{timeout:20000});
    await page.keyboard.press('ControlLeft');await page.waitForFunction(()=>document.querySelector('.stance-label')?.textContent.includes('CROUCHED'));
    await page.keyboard.down('KeyE');await page.waitForFunction(()=>document.querySelector('.stance-label')?.textContent.includes('LEAN RIGHT'));await page.keyboard.up('KeyE');
    await page.keyboard.down('KeyQ');await page.waitForFunction(()=>document.querySelector('.stance-label')?.textContent.includes('LEAN LEFT'));await page.keyboard.up('KeyQ');
    await page.keyboard.press('ControlLeft');await page.waitForFunction(()=>document.querySelector('.stance-label')?.textContent==='');
    await page.screenshot({path:'artifacts/production-gameplay.png'});
    await page.keyboard.press('Escape');await page.getByRole('button',{name:'Resume',exact:true}).waitFor();
    await page.getByRole('button',{name:'Resume',exact:true}).click();await page.waitForFunction(()=>!!document.pointerLockElement);
    report('Production pistol input/reload, toggle crouch, both lean controls, pause/resume and disabled debug hooks');
  }else{
    await ready();assert(await evaluate(()=>!!document.pointerLockElement));
    await evaluate(()=>{window.__gameTest.game.session.protection=999;});
    await verifyMap();assert.equal((await snap()).enemies.length,5);assert((await snap()).enemies.every(e=>e.kind==='pistol'));
    assert.equal((await snap()).supplies.filter(s=>s.kind==='health').length,5);
    const pos=await evaluate(()=>window.__gameTest.game.player.camera.position.z);
    await page.keyboard.down('KeyW');await page.waitForTimeout(450);await page.keyboard.up('KeyW');
    assert((await evaluate(()=>window.__gameTest.game.player.camera.position.z))>pos+.1);
    await evaluate(()=>{const g=window.__gameTest.game;g.player.spawn({x:0,z:-27});g.player.keys.add('ShiftLeft');g.player.keys.add('KeyW');g.player.update(.05,g.map.nav,true,'rifle',0);});
    assert((await evaluate(()=>window.__gameTest.game.player.camera.position.z))>-26.7);
    await evaluate(()=>{const g=window.__gameTest.game;g.player.clearInput();g.player.toggleCrouch();for(let i=0;i<8;i++)g.player.update(.05,g.map.nav,true,'rifle',0);});
    assert((await evaluate(()=>window.__gameTest.game.player.camera.position.y))<1.2);
    await evaluate(()=>{const g=window.__gameTest.game;g.player.clearInput();g.player.toggleCrouch();g.player.keys.add('Space');g.player.update(.05,g.map.nav,true,'rifle',0);});
    assert((await evaluate(()=>window.__gameTest.game.player.feet))>0);
    await evaluate(()=>window.__gameTest.game.player.clearInput());
    await page.mouse.down({button:'right'});await page.waitForTimeout(450);assert((await evaluate(()=>window.__gameTest.game.player.ads))>.6);await page.mouse.up({button:'right'});
    report('Pointer lock, movement, sprint, crouch, jump and ADS');
    await evaluate(()=>{const g=window.__gameTest.game;g.player.spawn({x:0,z:-27});g.player.camera.getViewMatrix(true);});
    const shots=(await snap()).stats.shotsFired;await page.mouse.click(550,380);assert((await snap()).stats.shotsFired>shots);
    await page.keyboard.press('KeyR');await advance(2.5);assert.equal(await evaluate(()=>window.__gameTest.game.session.inventory.rifle.loaded),30);
    const setup=async(distance=4)=>evaluate(()=>{const g=window.__gameTest.game;g.player.spawn({x:0,z:-26});g.session.protection=999;g.enemies.enemies.forEach(e=>{e.fireCooldown=999;e.grenadeCooldown=999;});const e=g.enemies.enemies.find(e=>e.alive);e.position.set(0,0,-22);e.route=[];e.repath=999;e.reaction=0;e.walking=false;e.root.computeWorldMatrix(true);e.root.getDescendants(false).forEach(m=>m.computeWorldMatrix(true));return e.id;});
    let id=await setup();
    for(let i=0;i<3;i++)await page.evaluate(id=>{window.__gameTest.aimEnemy(id,false);window.__gameTest.fire();},id);
    assert.equal((await snap()).stats.rifle,1);assert.equal((await snap()).stats.shotsHit,3);
    id=await setup();await page.keyboard.press('Digit2');await page.evaluate(id=>{window.__gameTest.aimEnemy(id,true);window.__gameTest.fire();},id);
    assert.equal((await snap()).stats.headshots,1);assert.equal((await snap()).stats.pistol,1);assert.equal((await snap()).stats.score,250);
    id=await setup();await evaluate(()=>{window.__gameTest.teleport(0,-23.5);});await page.keyboard.press('Digit3');await page.evaluate(id=>{window.__gameTest.aimEnemy(id,false);window.__gameTest.fire();},id);
    assert.equal((await snap()).stats.knife,1);report('Rifle firing/reload, three body hits, pistol headshot and knife kill');
    await evaluate(()=>{const g=window.__gameTest.game;g.player.spawn({x:0,z:-27});g.weapons.select('frag');g.weapons.cooldown=0;g.weapons.fire();});
    assert.equal(await evaluate(()=>window.__gameTest.game.session.inventory.frag),2);
    await advance(3);assert.equal(await evaluate(()=>window.__gameTest.game.projectiles.items.filter(p=>p.player).length),0);report('Thrown frag fuse, collision and detonation');
    await evaluate(()=>{const g=window.__gameTest.game;g.weapons.select('smoke');g.weapons.cooldown=0;g.weapons.fire();});await advance(5);
    assert.equal(await evaluate(()=>window.__gameTest.game.session.inventory.smoke),0);
    assert.equal(await evaluate(()=>window.__gameTest.game.effects.clouds.length),1);
    assert(await evaluate(()=>{const g=window.__gameTest.game,s=g.effects.clouds[0];return g.effects.obscured(s.position,s.position.add(g.player.forward().scale(20)));}));
    await evaluate(()=>{const g=window.__gameTest.game,s=g.effects.clouds[0];g.player.camera.position.copyFrom(s.position);});
    await page.screenshot({path:'artifacts/smoke.png'});report('Smoke inventory, dense visual volume and AI sight occlusion');
    await evaluate(()=>{const g=window.__gameTest.game;g.session.protection=0;g.session.health=200;const s=g.map.supplies.find(s=>s.kind==='health');g.player.spawn({x:s.position.x,z:s.position.z});g.interact();g.interact();});
    assert.equal((await snap()).health,1000);assert.equal((await snap()).supplies.filter(s=>s.used).length,1);
    await evaluate(()=>{const g=window.__gameTest.game;g.session.inventory.rifle.loaded=0;const s=g.map.supplies.find(s=>s.kind==='ammo');g.player.spawn({x:s.position.x,z:s.position.z});g.interact();g.session.inventory.rifle.fire();g.interact();});
    assert.equal((await snap()).ammo,149);report('Single-use health and complete ammo resupply');
    const before=(await snap()).remaining;
    await evaluate(()=>window.__gameTest.damage(2000));assert.equal((await snap()).state,'PlayerDead');
    await page.keyboard.press('Escape');await page.getByRole('button',{name:'Resume',exact:true}).waitFor();const paused=await snap();await advance(3);assert.equal((await snap()).remaining,paused.remaining);assert.equal((await snap()).respawn,paused.respawn);
    await page.getByRole('button',{name:'Resume',exact:true}).click();await page.waitForFunction(()=>!!document.pointerLockElement);
    const respawned=await evaluate(()=>{const t=window.__gameTest.snapshot().respawn;window.__gameTest.advance(t+.1);return window.__gameTest.snapshot();});assert.equal(respawned.state,'Playing');assert.equal(respawned.health,1000);assert(respawned.protection>4);assert(respawned.remaining<before-14.9);report('Player damage, death, 15s respawn, protection and paused timers');
    await evaluate(()=>{const g=window.__gameTest.game;g.session.protection=999;const p=g.map.props.find(p=>p.kind==='crate');g.damageProp(p,10,true);});
    assert(await evaluate(()=>window.__gameTest.game.map.props.find(p=>p.kind==='crate').destroyed));
    const barrel=await evaluate(()=>{const g=window.__gameTest.game;const p=g.map.props.find(p=>p.kind==='barrel');const e=g.enemies.enemies.find(e=>e.alive);if(e)e.position.copyFrom(p.position).addInPlace(g.player.forward().scale(2));g.damageProp(p,3,true);return p.kind;});
    await advance(1.7);assert(await evaluate(()=>window.__gameTest.game.map.props.find(p=>p.kind==='barrel').destroyed));assert((await snap()).stats.environment>0);report('Destructible collision removal, delayed fuel blast and environmental scoring');
    await evaluate(()=>{const g=window.__gameTest.game;const e=g.enemies.enemies.find(e=>e.alive);const s=g.map.enemySpawns.find(s=>!s.y&&Math.hypot(s.x,s.z+27)>25);e.position.set(s.x,0,s.z);e.route=[];e.repath=0;g.player.spawn({x:0,z:-27});});
    const start=await evaluate(()=>window.__gameTest.game.enemies.enemies.find(e=>e.alive).position.asArray());await advance(4);
    const end=await evaluate(()=>window.__gameTest.game.enemies.enemies.find(e=>e.alive).position.asArray());assert(Math.hypot(end[0]-start[0],end[2]-start[2])>1);report('Enemy pathfinding and actual movement around buildings');
    const stair=await evaluate(()=>{const g=window.__gameTest.game,r=g.map.nav.ramps[0];g.player.spawn({x:r.x,z:r.z-r.d/2+.1});for(let i=0;i<40;i++){g.map.nav.move(g.player.camera.position,0,.2,g.player.feet);g.player.feet=g.map.nav.ground(g.player.camera.position.x,g.player.camera.position.z,g.player.feet);}return g.player.feet;});assert(stair>3);report('Stair traversal to upper level');
    await page.screenshot({path:'artifacts/market-quarter.png'});
    await evaluate(()=>window.__gameTest.elapse(300));assert.equal((await snap()).state,'WaveComplete');
    await page.getByRole('button',{name:'Begin Wave 2'}).click();await ready();await verifyMap();assert.equal((await snap()).wave,1);assert.equal((await snap()).enemies.length,6);assert((await snap()).enemies.filter(e=>e.kind==='rifle').length>=4);assert((await snap()).enemies.every(e=>e.kind==='rifle'||e.kind==='pistol'));assert.equal((await snap()).supplies.filter(s=>s.used).length,0);
    await page.screenshot({path:'artifacts/residential-district.png'});report('Wave 1 results, intentional Wave 2 start and fresh map supplies');
    await evaluate(()=>{const g=window.__gameTest.game;g.session.protection=0;g.session.health=1000;g.player.spawn({x:0,z:-27});const e=g.enemies.enemies[0];e.position.set(0,0,-17);e.reaction=100;e.fireCooldown=0;e.grenadeCooldown=0;for(let i=0;i<300&&g.session.health>=1000;i++)g.enemies.update(.05);});
    assert((await snap()).health<1000);assert(await evaluate(()=>window.__gameTest.game.projectiles.items.some(p=>!p.player&&p.kind==='frag')));report('Enemy rifle fire, player damage and thrown enemy grenades');
    await evaluate(()=>window.__gameTest.elapse(300));await page.getByRole('button',{name:'Begin Wave 3'}).click();await ready();await verifyMap();assert.equal((await snap()).wave,2);assert.equal((await snap()).enemies.length,7);assert((await snap()).enemies.some(e=>e.kind==='rocket'));assert((await snap()).enemies.some(e=>e.kind==='bomber'));
    await evaluate(()=>{const g=window.__gameTest.game;g.session.protection=999;g.player.spawn({x:0,z:-31});const e=g.enemies.enemies.find(e=>e.kind==='rocket');e.position.set(0,0,-22);e.reaction=10;e.fireCooldown=0;e.repath=999;g.enemies.update(.05);});
    assert(await evaluate(()=>window.__gameTest.game.projectiles.items.some(p=>p.kind==='rocket')));
    await advance(2);assert(!await evaluate(()=>window.__gameTest.game.projectiles.items.some(p=>p.kind==='rocket')));report('Wave 3 visible rocket travel, collision and blast');
    await evaluate(()=>{const g=window.__gameTest.game;g.session.protection=0;g.session.health=1000;const p=g.player.camera.position.clone();g.projectiles.launch('rocket',p.add(g.player.forward().scale(2)),g.player.forward().scale(-24),false);g.projectiles.update(.12);});assert((await snap()).health<1000);report('Rocket collision with the player capsule');
    await evaluate(()=>{const g=window.__gameTest.game;g.session.health=1000;g.session.state='Playing';g.session.protection=999;g.player.spawn({x:0,z:-27});});
    await evaluate(()=>{const g=window.__gameTest.game;const b=g.enemies.enemies.find(e=>e.kind==='bomber'&&e.alive);b.position.set(0,0,-25);b.route=[];b.repath=999;b.warn=0;for(let i=0;i<24;i++)g.enemies.update(.05);});
    assert(!await evaluate(()=>window.__gameTest.game.enemies.enemies.some(e=>e.kind==='bomber'&&e.alive)));report('Recognisable bomber close approach and delayed detonation');
    await page.screenshot({path:'artifacts/ruined-crossing.png'});
    await evaluate(()=>window.__gameTest.elapse(300));assert.equal((await snap()).state,'GameComplete');
    assert(await page.getByRole('heading',{name:'Operation Complete'}).isVisible());assert(await page.getByRole('table').isVisible());await page.screenshot({path:'artifacts/results.png'});
    await page.getByRole('button',{name:'Play Again'}).click();await ready();assert.equal((await snap()).stats.score,0);assert.equal((await snap()).wave,0);report('Final per-wave/overall results and Play Again reset');
    assert(await evaluate(()=>window.__gameTest.game.audio.buffers.size>=80&&window.__gameTest.game.audio.context.state==='running'));report('Bundled audio decoded and Web Audio running');
  }
  assert(requests.every(url=>url.startsWith('http://localhost:')||url.startsWith('ws://localhost:')||url.startsWith('data:')||url.startsWith('blob:')),'External runtime request');
  assert.equal(errors.length,0,errors.join('\n'));report('No console errors or external runtime resource requests');
  await writeFile(`artifacts/${production?'production-':''}${process.env.BROWSER??'chromium'}-report.json`,JSON.stringify({passed,errors,requests,mouseInput:'Playwright mouse'},null,2));
}catch(e){await page.screenshot({path:'artifacts/failure.png'}).catch(()=>{});console.error('FAILED',e);console.error('HUD state:',await evaluate(()=>({weapon:document.querySelector('.weapon-name')?.textContent,ammo:document.querySelector('.ammo-value')?.textContent,status:document.querySelector('.status')?.textContent,lock:!!document.pointerLockElement,width:innerWidth,height:innerHeight})).catch(()=>null));console.error('Console errors:',errors);process.exitCode=1;}finally{await browser.close();}
