// Deliberate ES-module imports keep unrelated Babylon features out of the build.
export { Engine } from '@babylonjs/core/Engines/engine';
export { Scene } from '@babylonjs/core/scene';
export { Vector3, Quaternion, Matrix } from '@babylonjs/core/Maths/math.vector';
export { Color3, Color4 } from '@babylonjs/core/Maths/math.color';
export { Ray } from '@babylonjs/core/Culling/ray';
export { FreeCamera } from '@babylonjs/core/Cameras/freeCamera';
export { Mesh } from '@babylonjs/core/Meshes/mesh';
export { InstancedMesh } from '@babylonjs/core/Meshes/instancedMesh';
export { AbstractMesh } from '@babylonjs/core/Meshes/abstractMesh';
export { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder';
export { VertexData } from '@babylonjs/core/Meshes/mesh.vertexData';
export { TransformNode } from '@babylonjs/core/Meshes/transformNode';
export type { Node } from '@babylonjs/core/node';
export { PBRMaterial } from '@babylonjs/core/Materials/PBR/pbrMaterial';
export { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial';
export { Material } from '@babylonjs/core/Materials/material';
export { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture';
export { Texture } from '@babylonjs/core/Materials/Textures/texture';
export { CubeTexture } from '@babylonjs/core/Materials/Textures/cubeTexture';
export { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight';
export { DirectionalLight } from '@babylonjs/core/Lights/directionalLight';
export { PointLight } from '@babylonjs/core/Lights/pointLight';
export { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator';
export { HavokPlugin } from '@babylonjs/core/Physics/v2/Plugins/havokPlugin';
export { PhysicsAggregate } from '@babylonjs/core/Physics/v2/physicsAggregate';
export { PhysicsShapeType } from '@babylonjs/core/Physics/v2/IPhysicsEnginePlugin';
export { AssetContainer } from '@babylonjs/core/assetContainer';
export { LoadAssetContainerAsync } from '@babylonjs/core/Loading/sceneLoader';
export { AnimationGroup } from '@babylonjs/core/Animations/animationGroup';
export { AnimationGroupMask, AnimationGroupMaskMode } from '@babylonjs/core/Animations/animationGroupMask';
export { ParticleSystem } from '@babylonjs/core/Particles/particleSystem';
export { DefaultRenderingPipeline } from '@babylonjs/core/PostProcesses/RenderPipeline/Pipelines/defaultRenderingPipeline';
export { ImageProcessingConfiguration } from '@babylonjs/core/Materials/imageProcessingConfiguration';
export { ColorCurves } from '@babylonjs/core/Materials/colorCurves';
import '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent';
import '@babylonjs/core/Culling/ray';
import '@babylonjs/core/Materials/Textures/Loaders/envTextureLoader';
import '@babylonjs/core/Animations/animatable';
import '@babylonjs/core/Rendering/depthRendererSceneComponent';
import '@babylonjs/core/Engines/Extensions/engine.multiRender';
import '@babylonjs/loaders/glTF/glTFFileLoader';
import '@babylonjs/loaders/glTF/2.0/glTFLoader';
